version: '3'
services:
  app_department:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://dbdepartament:3306/department?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: root
    restart: always
    depends_on:
      dbdepartament:
          condition: service_healthy
  dbdepartament:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: department
    restart: always
    healthcheck:        
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10